### ISSUE TITLE
Unauthorized issue

### ISSUE THREAD

**Issue by LightC0d3r** [discord/discord-example-app#25]
When I ran npm run register it said 401
Error: {"message":"401: Unauthorized","code":0}
    at DiscordRequest (file:///C:/Users/kbrow/Downloads/discord-example-app/utils.js:36:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InstallGlobalCommands (file:///C:/Users/kbrow/Downloads/discord-example-app/utils.js:48:5) 
when I put everything in correctly in the .env file

**Comment by JayyDoesDev** [comment]
Is the bot token or application id correct? Make sure these are correct.

**Comment by LightC0d3r** [comment]
Found out that I had to take away the symbols that have the indicators inside of them I'm stupid
