### ISSUE TITLE
Errors During "npm run register"

### ISSUE THREAD

**Issue by cinnafin** [discord/discord-example-app#46]
I'm receiving the following error message when I try to complete "npm run register" step. I've identified the error lies within the utils.js file but I'm not sure what needs to change. Any ideas?

401
Error: {"message":"401: Unauthorized","code":0}
    at DiscordRequest (file:///C:/Users/sjdel/OneDrive/Desktop/VSC%20Projects/discord-example-app/utils.js:36:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InstallGlobalCommands (file:///C:/Users/sjdel/OneDrive/Desktop/VSC%20Projects/discord-example-app/utils.js:48:5)

**Comment by xgenos** [comment]
make sure to change the file name from `.env.sample` to `.env`  and check the tokens are mentioned correctly
